name: CI (Node.js)

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        required: false
        default: 16
    secrets:
      aws-id:
        required: true
      aws-secret:
        required: true
      git-read-key:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-id }}
          aws-secret-access-key: ${{ secrets.aws-secret }}
          aws-region: eu-central-1

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.git-read-key }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check is coverage enabled
        id: coverage-enabled
        run: echo "::set-output name=coverage-enabled::$(npm run | grep "test:cov")"

      - name: Test
        if: steps.coverage-enabled.outputs.coverage-enabled == ''
        run: npm run test --if-present

      - name: Test + Coverage
        if: steps.coverage-enabled.outputs.coverage-enabled
        run: npm run test:cov --if-present

      - name: Build
        run: |
          npm run build --if-present
          npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present -- --max-warnings=0

      - name: Coverage - Generate NYC report
        if: steps.coverage-enabled.outputs.coverage-enabled
        run: |
          npx nyc report \
            --reporter json-summary \
            --exclude-after-remap false

      - name: Coverage - Create Comment Template
        if: steps.coverage-enabled.outputs.coverage-enabled
        run: |
          touch template.md
          echo "## Coverage Report

          Commit: [{{short_commit_sha}}]({{commit_link}})

          <details>
          <summary>Details (all files)</summary>
          {{files_coverage_table}}
          </details>" >> template.md

      - name: Coverage - Send to Pull Request
        if: steps.coverage-enabled.outputs.coverage-enabled
        uses: sidx1024/report-nyc-coverage-github-action@873d5033d5a27e263ec68115ae1d378100cacff2
        with:
          coverage_file: tmp/coverage-report/coverage-summary.json
          comment_template_file: template.md
          files_coverage_table_output_type_order: SBFL
