name: CI (Node.js)

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        required: false
        default: 16
    secrets:
      aws-id:
        required: true
      aws-secret:
        required: true
      git-read-key:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-id }}
          aws-secret-access-key: ${{ secrets.aws-secret }}
          aws-region: eu-central-1

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.git-read-key }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test --if-present

      - name: Build
        run: npm run build --if-present

      - name: Lint
        run: npm run lint --if-present -- --max-warnings=0
