name: Serverless Deploy (Node.js)

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
      node-version:
        type: number
        required: false
        default: 16
    secrets:
      aws-id:
        required: true
      aws-secret:
        required: true
      git-read-key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-id }}
          aws-secret-access-key: ${{ secrets.aws-secret }}
          aws-region: eu-central-1

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.git-read-key }}

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: npm run sls:deploy -- --stage=${{ env.STAGE }} ${{ inputs.stage == "prod" && '--conceal' || '' }}
